name: workouts
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #database
  drift: ^2.19.1+1
  drift_flutter: ^0.1.0
  #logger
  l: ^4.0.2
  #models
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  #serialization
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3_flutter_libs: ^0.5.24
  uuid: ^4.4.2
  firebase_messaging: ^15.0.3
  firebase: ^9.0.3
  firebase_core: ^3.2.0
  meta: ^1.15.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  #database
  drift_dev: ^2.19.1
  #codegen
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

